# -*- coding: utf-8 -*-
{
    'name': 'SKUVAULT Integration',
    'category': 'Website',
    'author': "Vraja Technologies",
    'version': '15.0.21.02.2023',
    'summary': """ """,
    'description': """""",
    'depends': ['delivery', 'import_inventory'],
    'data': [
        'security/ir.model.access.csv',
        'view/sale_order.xml',
        'view/stock_warehouse.xml',
        'view/skuvault_operation_details.xml',
        'view/product_template.xml',
        'view/stock_picking.xml',
        'data/skuvault_inventory_crone.xml',
        'data/skuvault_import_product_crone.xml',
    ],
    'images': [''],
    'maintainer': 'Vraja Technologies',
    'website': 'www.vrajatechnologies.com',
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'currency': 'EUR',
    'license': 'OPL-1',
}
