from . import shopify_instance_integration
from . import stock_picking
from . import sale_order
from . import order_workflow_automation
from . import shopify_locations
from . import shopify_payment_gateway
from . import shopify_financial_status_configuration
from . import shopify_log
from . import order_data_queue
from . import product_pricelist
from . import product_attribute
from . import product_attribute_value
from . import product_listing
from . import product_listing_item
from . import shopify_product_image
from . import product_data_queue
from . import inventory_data_queue
from . import delivery_carrier
from . import customer_data_queue
from . import res_partner
from . import shopify_risk_order
from . import sale_order_line
from . import shopify_webhook
